service: siatech-kioscos-dblayer
frameworkVersion: "^3.40.0"

# --- Provider obligatorio ---
provider:
  name: aws
  runtime: nodejs18.x        # valor por defecto (las capas lo sobre-escriben)
  region: us-east-2          # opcional; puedes omitir y pasar --region al deploy
  stage: ${opt:stage, 'dev'} # stage por parámetro o dev

# --- Capas --------------------------------------------------------
layers:
  NodeDbHelper: 
    path: node-layer
    description: "Mongo client + /opt/db helper"
    compatibleRuntimes: [nodejs18.x]
    retain: true

  PythonDbHelper:
    path: python-layer
    description: "PyMongo + /opt/db helper"
    compatibleRuntimes: [python3.11]
    retain: true

# Empaquetar solo las carpetas de layer
package:
  patterns:
    - node-layer/**
    - python-layer/**
